name: cfssl # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: SSL tools - cfssl, cfssljson, mkbundle, multirootca # 79 char long summary
description: |
  A set of SSL manipulation tools, that DevOps regularly install via curl and mv,
  neatly put in one package.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  cfssl:
    command: bin/cfssl
    plugs:
      - home
  cfssljson:
    command: bin/cfssljson
    plugs:
      - home
  cfssl-scan:
    command: bin/cfssl-scan
    plugs:
      - home
  cfssl-newkey:
    command: bin/cfssl-newkey
    plugs:
      - home
  cfssl-certinfo:
    command: bin/cfssl-certinfo
    plugs:
      - home
  cfssl-bundle:
    command: bin/cfssl-bundle
    plugs:
      - home
  mkbundle:
    command: bin/mkbundle
    plugs:
      - home
  multirootca:
    command: bin/multirootca
    plugs:
      - home

parts:
  cfssl:
    plugin: go
    source-type: git
    source: https://github.com/cloudflare/cfssl

# code: language=yaml
